version: "3.10"
services:

    backend:
      build: ./backend/
      volumes:
        - ./backend:/code
      ports:
        - "8000:8000"

    frontend:
      build: ./frontend/
      volumes:
        - ./frontend:/code
      ports:
        - "3000:3000"