version: "3.10"
services:

    backend:
      image: backend_image
      build: ./backend/
      volumes:
        - ./backend:/code
      ports:
        - "8000:8000"

    frontend:
      image: frontend_image
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - ./frontend:/code
      ports:
        - "80:80"
        - "3000:3000"