// Public Stats Constants

export const PUBLIC_STATS_REQUEST = "PUBLIC_STATS_REQUEST";
export const PUBLIC_STATS_SUCCESS = "PUBLIC_STATS_SUCCESS";
export const PUBLIC_STATS_FAILURE = "PUBLIC_STATS_FAILURE";
