// Review Stats Data Constants

export const REVIEW_STATS_DATA_REQUEST = "REVIEW_STATS_DATA_REQUEST";
export const REVIEW_STATS_DATA_SUCCESS = "REVIEW_STATS_DATA_SUCCESS";
export const REVIEW_STATS_DATA_FAILURE = "REVIEW_STATS_DATA_FAILURE";
