// Review Statics Constants

export const REVIEW_STATICS_REQUEST = "REVIEW_STATICS_REQUEST";
export const REVIEW_STATICS_SUCCESS = "REVIEW_STATICS_SUCCESS";
export const REVIEW_STATICS_FAILURE = "REVIEW_STATICS_FAILURE";
